== Safari^® Books Online

	_Safari Books Online_ is an on-demand digial library that delivers expert
	content in both book and video form from the world's leading authors in
	technology and business.

Technology professionals, software developers, web designers, and business and
creative professionals use Safari Books Online as their primary resource for
research, problem solving, learning, and certificate training.

Safari Books Online offers a range of plans and pricing for enterprise,
government, education, and individuals.

Members have access to thousands of books, training videos, and prepublication
manuscripts in one fully searchable database from publishers like O'Reilly
Media, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press,
Sams, Que, Peachpit Press, Focal Press, Cisco Press, John Wiley & Sons,
Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress,
Manning, New Riders, McGraw-Hill, Jones & Bartlett, Course Technology, and
hundreds more. For more information about Safari Books Online, please visit us
online.
